<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class WilayahKabKotaSeeder extends Seeder
{
    public function run(): void
    {
        $kabkota = [
            // 1) Provinsi Aceh (11)
            ['1171', 'Kota Banda Aceh'],
            ['1172', 'Kota Langsa'],
            ['1173', 'Kota Lhokseumawe'],
            ['1174', 'Kota Sabang'],
            ['1175', 'Kota Subulussalam'],
            ['1101', 'Kabupaten Aceh Barat'],
            ['1102', 'Kabupaten Aceh Barat Daya'],
            ['1103', 'Kabupaten Aceh Besar'],
            ['1104', 'Kabupaten Aceh Jaya'],
            ['1105', 'Kabupaten Aceh Selatan'],
            ['1106', 'Kabupaten Aceh Singkil'],
            ['1107', 'Kabupaten Aceh Tamiang'],
            ['1108', 'Kabupaten Aceh Tengah'],
            ['1109', 'Kabupaten Aceh Tenggara'],
            ['1110', 'Kabupaten Aceh Timur'],
            ['1111', 'Kabupaten Aceh Utara'],
            ['1112', 'Kabupaten Bener Meriah'],
            ['1113', 'Kabupaten Bireuen'],
            ['1114', 'Kabupaten Gayo Lues'],
            ['1115', 'Kabupaten Nagan Raya'],
            ['1116', 'Kabupaten Pidie'],
            ['1117', 'Kabupaten Pidie Jaya'],
            ['1118', 'Kabupaten Simeulue'],

            // 2) Provinsi Sumatera Utara (12)
            ['1271', 'Kota Medan'],
            ['1272', 'Kota Binjai'],
            ['1273', 'Kota Gunungsitoli'],
            ['1274', 'Kota Padang Sidempuan'],
            ['1275', 'Kota Pematang Siantar'],
            ['1276', 'Kota Sibolga'],
            ['1277', 'Kota Tanjungbalai'],
            ['1278', 'Kota Tebing Tinggi'],
            ['1201', 'Kabupaten Asahan'],
            ['1202', 'Kabupaten Batu Bara'],
            ['1203', 'Kabupaten Dairi'],
            ['1204', 'Kabupaten Deli Serdang'],
            ['1205', 'Kabupaten Humbang Hasundutan'],
            ['1206', 'Kabupaten Karo'],
            ['1207', 'Kabupaten Labuhanbatu'],
            ['1208', 'Kabupaten Labuhanbatu Selatan'],
            ['1209', 'Kabupaten Labuhanbatu Utara'],
            ['1210', 'Kabupaten Langkat'],
            ['1211', 'Kabupaten Mandailing Natal'],
            ['1212', 'Kabupaten Nias'],
            ['1213', 'Kabupaten Nias Barat'],
            ['1214', 'Kabupaten Nias Selatan'],
            ['1215', 'Kabupaten Nias Utara'],
            ['1216', 'Kabupaten Padang Lawas'],
            ['1217', 'Kabupaten Padang Lawas Utara'],
            ['1218', 'Kabupaten Pakpak Bharat'],
            ['1219', 'Kabupaten Samosir'],
            ['1220', 'Kabupaten Serdang Bedagai'],
            ['1221', 'Kabupaten Simalungun'],
            ['1222', 'Kabupaten Tapanuli Selatan'],
            ['1223', 'Kabupaten Tapanuli Tengah'],
            ['1224', 'Kabupaten Tapanuli Utara'],
            ['1225', 'Kabupaten Toba'],

            // 3) Provinsi Riau (14)
            ['1471', 'Kota Pekanbaru'],
            ['1472', 'Kota Dumai'],
            ['1401', 'Kabupaten Bengkalis'],
            ['1402', 'Kabupaten Indragiri Hilir'],
            ['1403', 'Kabupaten Indragiri Hulu'],
            ['1404', 'Kabupaten Kampar'],
            ['1405', 'Kabupaten Kepulauan Meranti'],
            ['1406', 'Kabupaten Kuantan Singingi'],
            ['1407', 'Kabupaten Pelalawan'],
            ['1408', 'Kabupaten Rokan Hilir'],
            ['1409', 'Kabupaten Rokan Hulu'],
            ['1410', 'Kabupaten Siak'],

            // 4) Provinsi Kepulauan Riau (21)
            ['2171', 'Kota Tanjungpinang'],
            ['2172', 'Kota Batam'],
            ['2101', 'Kabupaten Bintan'],
            ['2102', 'Kabupaten Karimun'],
            ['2103', 'Kabupaten Kepulauan Anambas'],
            ['2104', 'Kabupaten Lingga'],
            ['2105', 'Kabupaten Natuna'],

            // 5) Provinsi Sumatera Barat (13)
            ['1371', 'Kota Padang'],
            ['1372', 'Kota Bukittinggi'],
            ['1373', 'Kota Padang Panjang'],
            ['1374', 'Kota Pariaman'],
            ['1375', 'Kota Payakumbuh'],
            ['1376', 'Kota Sawahlunto'],
            ['1377', 'Kota Solok'],
            ['1301', 'Kabupaten Kepulauan Mentawai'],
            ['1302', 'Kabupaten Agam'],
            ['1303', 'Kabupaten Dharmasraya'],
            ['1304', 'Kabupaten Lima Puluh Kota'],
            ['1305', 'Kabupaten Padang Pariaman'],
            ['1306', 'Kabupaten Pasaman'],
            ['1307', 'Kabupaten Pasaman Barat'],
            ['1308', 'Kabupaten Pesisir Selatan'],
            ['1309', 'Kabupaten Sijunjung'],
            ['1310', 'Kabupaten Solok'],
            ['1311', 'Kabupaten Solok Selatan'],
            ['1312', 'Kabupaten Tanah Datar'],

            // 6) Provinsi Sumatera Selatan (16)
            ['1671', 'Kota Palembang'],
            ['1672', 'Kota Prabumulih'],
            ['1673', 'Kota Lubuklinggau'],
            ['1674', 'Kota Pagar Alam'],
            ['1601', 'Kabupaten Ogan Komering Ulu'],
            ['1602', 'Kabupaten Ogan Komering Ulu Timur'],
            ['1603', 'Kabupaten Ogan Komering Ulu Selatan'],
            ['1604', 'Kabupaten Ogan Komering Ilir'],
            ['1605', 'Kabupaten Ogan Ilir'],
            ['1606', 'Kabupaten Muara Enim'],
            ['1607', 'Kabupaten Penukal Abab Lematang Ilir'],
            ['1608', 'Kabupaten Lahat'],
            ['1609', 'Kabupaten Empat Lawang'],
            ['1610', 'Kabupaten Musi Rawas'],
            ['1611', 'Kabupaten Musi Rawas Utara'],
            ['1612', 'Kabupaten Musi Banyuasin'],
            ['1613', 'Kabupaten Banyuasin'],

            // 7) Provinsi Jambi (15)
            ['1571', 'Kota Jambi'],
            ['1572', 'Kota Sungai Penuh'],
            ['1501', 'Kabupaten Batanghari'],
            ['1502', 'Kabupaten Bungo'],
            ['1503', 'Kabupaten Kerinci'],
            ['1504', 'Kabupaten Merangin'],
            ['1505', 'Kabupaten Muaro Jambi'],
            ['1506', 'Kabupaten Sarolangun'],
            ['1507', 'Kabupaten Tanjung Jabung Barat'],
            ['1508', 'Kabupaten Tanjung Jabung Timur'],
            ['1509', 'Kabupaten Tebo'],

            // 8) Provinsi Bengkulu (17)
            ['1771', 'Kota Bengkulu'],
            ['1701', 'Kabupaten Bengkulu Selatan'],
            ['1702', 'Kabupaten Bengkulu Tengah'],
            ['1703', 'Kabupaten Bengkulu Utara'],
            ['1704', 'Kabupaten Kaur'],
            ['1705', 'Kabupaten Kepahiang'],
            ['1706', 'Kabupaten Lebong'],
            ['1707', 'Kabupaten Mukomuko'],
            ['1708', 'Kabupaten Rejang Lebong'],
            ['1709', 'Kabupaten Seluma'],

            // 9) Provinsi Kepulauan Bangka Belitung (19)
            ['1971', 'Kota Pangkalpinang'],
            ['1901', 'Kabupaten Bangka'],
            ['1902', 'Kabupaten Bangka Barat'],
            ['1903', 'Kabupaten Bangka Tengah'],
            ['1904', 'Kabupaten Bangka Selatan'],
            ['1905', 'Kabupaten Belitung'],
            ['1906', 'Kabupaten Belitung Timur'],

            // 10) Provinsi Lampung (18)
            ['1871', 'Kota Bandar Lampung'],
            ['1872', 'Kota Metro'],
            ['1801', 'Kabupaten Lampung Barat'],
            ['1802', 'Kabupaten Lampung Selatan'],
            ['1803', 'Kabupaten Lampung Tengah'],
            ['1804', 'Kabupaten Lampung Timur'],
            ['1805', 'Kabupaten Lampung Utara'],
            ['1806', 'Kabupaten Mesuji'],
            ['1807', 'Kabupaten Pesawaran'],
            ['1808', 'Kabupaten Pesisir Barat'],
            ['1809', 'Kabupaten Pringsewu'],
            ['1810', 'Kabupaten Tanggamus'],
            ['1811', 'Kabupaten Tulang Bawang'],
            ['1812', 'Kabupaten Tulang Bawang Barat'],
            ['1813', 'Kabupaten Way Kanan'],

            // 11) Provinsi Banten (36)
            ['3671', 'Kota Serang'],
            ['3672', 'Kota Tangerang'],
            ['3673', 'Kota Tangerang Selatan'],
            ['3674', 'Kota Cilegon'],
            ['3601', 'Kabupaten Pandeglang'],
            ['3602', 'Kabupaten Lebak'],
            ['3603', 'Kabupaten Tangerang'],
            ['3604', 'Kabupaten Serang'],

            // 12) Provinsi DKI Jakarta (31)
            ['3171', 'Kota Jakarta Pusat'],
            ['3172', 'Kota Jakarta Barat'],
            ['3173', 'Kota Jakarta Selatan'],
            ['3174', 'Kota Jakarta Utara'],
            ['3175', 'Kota Jakarta Timur'],
            ['3101', 'Kabupaten Kepulauan Seribu'],

            // 13) Provinsi Jawa Barat (32)
            ['3271', 'Kota Bandung'],
            ['3272', 'Kota Banjar'],
            ['3273', 'Kota Bekasi'],
            ['3274', 'Kota Bogor'],
            ['3275', 'Kota Cimahi'],
            ['3276', 'Kota Cirebon'],
            ['3277', 'Kota Depok'],
            ['3278', 'Kota Sukabumi'],
            ['3279', 'Kota Tasikmalaya'],
            ['3201', 'Kabupaten Bandung'],
            ['3202', 'Kabupaten Bandung Barat'],
            ['3203', 'Kabupaten Bekasi'],
            ['3204', 'Kabupaten Bogor'],
            ['3205', 'Kabupaten Ciamis'],
            ['3206', 'Kabupaten Cianjur'],
            ['3207', 'Kabupaten Cirebon'],
            ['3208', 'Kabupaten Garut'],
            ['3209', 'Kabupaten Indramayu'],
            ['3210', 'Kabupaten Karawang'],
            ['3211', 'Kabupaten Kuningan'],
            ['3212', 'Kabupaten Majalengka'],
            ['3213', 'Kabupaten Pangandaran'],
            ['3214', 'Kabupaten Purwakarta'],
            ['3215', 'Kabupaten Subang'],
            ['3216', 'Kabupaten Sukabumi'],
            ['3217', 'Kabupaten Sumedang'],
            ['3218', 'Kabupaten Tasikmalaya'],

            // 14) Provinsi Jawa Tengah (33)
            ['3371', 'Kota Semarang'],
            ['3372', 'Kota Magelang'],
            ['3373', 'Kota Pekalongan'],
            ['3374', 'Kota Salatiga'],
            ['3375', 'Kota Surakarta'],
            ['3376', 'Kota Tegal'],
            ['3301', 'Kabupaten Banjarnegara'],
            ['3302', 'Kabupaten Banyumas'],
            ['3303', 'Kabupaten Batang'],
            ['3304', 'Kabupaten Blora'],
            ['3305', 'Kabupaten Boyolali'],
            ['3306', 'Kabupaten Brebes'],
            ['3307', 'Kabupaten Cilacap'],
            ['3308', 'Kabupaten Demak'],
            ['3309', 'Kabupaten Grobogan'],
            ['3310', 'Kabupaten Jepara'],
            ['3311', 'Kabupaten Karanganyar'],
            ['3312', 'Kabupaten Kebumen'],
            ['3313', 'Kabupaten Kendal'],
            ['3314', 'Kabupaten Klaten'],
            ['3315', 'Kabupaten Kudus'],
            ['3316', 'Kabupaten Magelang'],
            ['3317', 'Kabupaten Pati'],
            ['3318', 'Kabupaten Pekalongan'],
            ['3319', 'Kabupaten Pemalang'],
            ['3320', 'Kabupaten Purbalingga'],
            ['3321', 'Kabupaten Purworejo'],
            ['3322', 'Kabupaten Rembang'],
            ['3323', 'Kabupaten Semarang'],
            ['3324', 'Kabupaten Sragen'],
            ['3325', 'Kabupaten Sukoharjo'],
            ['3326', 'Kabupaten Tegal'],
            ['3327', 'Kabupaten Temanggung'],
            ['3328', 'Kabupaten Wonogiri'],
            ['3329', 'Kabupaten Wonosobo'],

            // 15) Provinsi Daerah Istimewa Yogyakarta (34)
            ['3471', 'Kota Yogyakarta'],
            ['3401', 'Kabupaten Bantul'],
            ['3402', 'Kabupaten Gunungkidul'],
            ['3403', 'Kabupaten Kulon Progo'],
            ['3404', 'Kabupaten Sleman'],

            // 16) Provinsi Jawa Timur (35)
            ['3571', 'Kota Surabaya'],
            ['3572', 'Kota Malang'],
            ['3573', 'Kota Kediri'],
            ['3574', 'Kota Madiun'],
            ['3575', 'Kota Blitar'],
            ['3576', 'Kota Mojokerto'],
            ['3577', 'Kota Pasuruan'],
            ['3578', 'Kota Probolinggo'],
            ['3579', 'Kota Batu'],
            ['3501', 'Kabupaten Bangkalan'],
            ['3502', 'Kabupaten Banyuwangi'],
            ['3503', 'Kabupaten Blitar'],
            ['3504', 'Kabupaten Bojonegoro'],
            ['3505', 'Kabupaten Bondowoso'],
            ['3506', 'Kabupaten Gresik'],
            ['3507', 'Kabupaten Jember'],
            ['3508', 'Kabupaten Jombang'],
            ['3509', 'Kabupaten Kediri'],
            ['3510', 'Kabupaten Lamongan'],
            ['3511', 'Kabupaten Lumajang'],
            ['3512', 'Kabupaten Madiun'],
            ['3513', 'Kabupaten Magetan'],
            ['3514', 'Kabupaten Malang'],
            ['3515', 'Kabupaten Mojokerto'],
            ['3516', 'Kabupaten Nganjuk'],
            ['3517', 'Kabupaten Ngawi'],
            ['3518', 'Kabupaten Pacitan'],
            ['3519', 'Kabupaten Pamekasan'],
            ['3520', 'Kabupaten Pasuruan'],
            ['3521', 'Kabupaten Ponorogo'],
            ['3522', 'Kabupaten Probolinggo'],
            ['3523', 'Kabupaten Sampang'],
            ['3524', 'Kabupaten Sidoarjo'],
            ['3525', 'Kabupaten Situbondo'],
            ['3526', 'Kabupaten Sumenep'],
            ['3527', 'Kabupaten Trenggalek'],
            ['3528', 'Kabupaten Tuban'],
            ['3529', 'Kabupaten Tulungagung'],

            // 17) Provinsi Bali (51)
            ['5171', 'Kota Denpasar'],
            ['5101', 'Kabupaten Badung'],
            ['5102', 'Kabupaten Bangli'],
            ['5103', 'Kabupaten Buleleng'],
            ['5104', 'Kabupaten Gianyar'],
            ['5105', 'Kabupaten Jembrana'],
            ['5106', 'Kabupaten Karangasem'],
            ['5107', 'Kabupaten Klungkung'],
            ['5108', 'Kabupaten Tabanan'],

            // 18) Provinsi Nusa Tenggara Barat (52)
            ['5271', 'Kota Mataram'],
            ['5272', 'Kota Bima'],
            ['5201', 'Kabupaten Lombok Barat'],
            ['5202', 'Kabupaten Lombok Tengah'],
            ['5203', 'Kabupaten Lombok Timur'],
            ['5204', 'Kabupaten Lombok Utara'],
            ['5205', 'Kabupaten Sumbawa'],
            ['5206', 'Kabupaten Sumbawa Barat'],
            ['5207', 'Kabupaten Dompu'],
            ['5208', 'Kabupaten Bima'],

            // 19) Provinsi Nusa Tenggara Timur (53)
            ['5371', 'Kota Kupang'],
            ['5301', 'Kabupaten Alor'],
            ['5302', 'Kabupaten Belu'],
            ['5303', 'Kabupaten Ende'],
            ['5304', 'Kabupaten Flores Timur'],
            ['5305', 'Kabupaten Kupang'],
            ['5306', 'Kabupaten Lembata'],
            ['5307', 'Kabupaten Malaka'],
            ['5308', 'Kabupaten Manggarai'],
            ['5309', 'Kabupaten Manggarai Barat'],
            ['5310', 'Kabupaten Manggarai Timur'],
            ['5311', 'Kabupaten Nagekeo'],
            ['5312', 'Kabupaten Ngada'],
            ['5313', 'Kabupaten Rote Ndao'],
            ['5314', 'Kabupaten Sabu Raijua'],
            ['5315', 'Kabupaten Sikka'],
            ['5316', 'Kabupaten Sumba Barat'],
            ['5317', 'Kabupaten Sumba Barat Daya'],
            ['5318', 'Kabupaten Sumba Tengah'],
            ['5319', 'Kabupaten Sumba Timur'],
            ['5320', 'Kabupaten Timor Tengah Selatan'],
            ['5321', 'Kabupaten Timor Tengah Utara'],

            // 20) Provinsi Kalimantan Barat (61)
            ['6171', 'Kota Pontianak'],
            ['6172', 'Kota Singkawang'],
            ['6101', 'Kabupaten Sambas'],
            ['6102', 'Kabupaten Bengkayang'],
            ['6103', 'Kabupaten Landak'],
            ['6104', 'Kabupaten Mempawah'],
            ['6105', 'Kabupaten Sanggau'],
            ['6106', 'Kabupaten Ketapang'],
            ['6107', 'Kabupaten Sintang'],
            ['6108', 'Kabupaten Kapuas Hulu'],
            ['6109', 'Kabupaten Sekadau'],
            ['6110', 'Kabupaten Melawi'],
            ['6111', 'Kabupaten Kubu Raya'],
            ['6112', 'Kabupaten Kayong Utara'],

            // 21) Provinsi Kalimantan Selatan (63)
            ['6371', 'Kota Banjarmasin'],
            ['6372', 'Kota Banjarbaru'],
            ['6301', 'Kabupaten Balangan'],
            ['6302', 'Kabupaten Banjar'],
            ['6303', 'Kabupaten Barito Kuala'],
            ['6304', 'Kabupaten Hulu Sungai Selatan'],
            ['6305', 'Kabupaten Hulu Sungai Tengah'],
            ['6306', 'Kabupaten Hulu Sungai Utara'],
            ['6307', 'Kabupaten Kotabaru'],
            ['6308', 'Kabupaten Tabalong'],
            ['6309', 'Kabupaten Tanah Bumbu'],
            ['6310', 'Kabupaten Tanah Laut'],
            ['6311', 'Kabupaten Tapin'],

            // 22) Provinsi Kalimantan Tengah (62)
            ['6271', 'Kota Palangka Raya'],
            ['6201', 'Kabupaten Barito Selatan'],
            ['6202', 'Kabupaten Barito Timur'],
            ['6203', 'Kabupaten Barito Utara'],
            ['6204', 'Kabupaten Gunung Mas'],
            ['6205', 'Kabupaten Kapuas'],
            ['6206', 'Kabupaten Katingan'],
            ['6207', 'Kabupaten Kotawaringin Barat'],
            ['6208', 'Kabupaten Kotawaringin Timur'],
            ['6209', 'Kabupaten Lamandau'],
            ['6210', 'Kabupaten Murung Raya'],
            ['6211', 'Kabupaten Pulang Pisau'],
            ['6212', 'Kabupaten Seruyan'],
            ['6213', 'Kabupaten Sukamara'],

            // 23) Provinsi Kalimantan Timur (64)
            ['6471', 'Kota Samarinda'],
            ['6472', 'Kota Balikpapan'],
            ['6473', 'Kota Bontang'],
            ['6401', 'Kabupaten Kutai Kartanegara'],
            ['6402', 'Kabupaten Kutai Timur'],
            ['6403', 'Kabupaten Kutai Barat'],
            ['6404', 'Kabupaten Berau'],
            ['6405', 'Kabupaten Paser'],
            ['6406', 'Kabupaten Penajam Paser Utara'],
            ['6407', 'Kabupaten Mahakam Ulu'],

            // 24) Provinsi Kalimantan Utara (65)
            ['6571', 'Kota Tarakan'],
            ['6501', 'Kabupaten Bulungan'],
            ['6502', 'Kabupaten Malinau'],
            ['6503', 'Kabupaten Nunukan'],
            ['6504', 'Kabupaten Tana Tidung'],

            // 25) Provinsi Sulawesi Selatan (73)
            ['7371', 'Kota Makassar'],
            ['7372', 'Kota Palopo'],
            ['7373', 'Kota Parepare'],
            ['7301', 'Kabupaten Bantaeng'],
            ['7302', 'Kabupaten Barru'],
            ['7303', 'Kabupaten Bone'],
            ['7304', 'Kabupaten Bulukumba'],
            ['7305', 'Kabupaten Enrekang'],
            ['7306', 'Kabupaten Gowa'],
            ['7307', 'Kabupaten Jeneponto'],
            ['7308', 'Kabupaten Kepulauan Selayar'],
            ['7309', 'Kabupaten Luwu'],
            ['7310', 'Kabupaten Luwu Timur'],
            ['7311', 'Kabupaten Luwu Utara'],
            ['7312', 'Kabupaten Maros'],
            ['7313', 'Kabupaten Pangkajene dan Kepulauan (Pangkep)'],
            ['7314', 'Kabupaten Pinrang'],
            ['7315', 'Kabupaten Sidenreng Rappang (Sidrap)'],
            ['7316', 'Kabupaten Sinjai'],
            ['7317', 'Kabupaten Soppeng'],
            ['7318', 'Kabupaten Takalar'],
            ['7319', 'Kabupaten Tana Toraja'],
            ['7320', 'Kabupaten Toraja Utara'],
            ['7321', 'Kabupaten Wajo'],

            // 26) Provinsi Sulawesi Utara (71)
            ['7171', 'Kota Manado'],
            ['7172', 'Kota Bitung'],
            ['7173', 'Kota Kotamobagu'],
            ['7174', 'Kota Tomohon'],
            ['7101', 'Kabupaten Bolaang Mongondow'],
            ['7102', 'Kabupaten Bolaang Mongondow Selatan'],
            ['7103', 'Kabupaten Bolaang Mongondow Timur'],
            ['7104', 'Kabupaten Bolaang Mongondow Utara'],
            ['7105', 'Kabupaten Kepulauan Sangihe'],
            ['7106', 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)'],
            ['7107', 'Kabupaten Kepulauan Talaud'],
            ['7108', 'Kabupaten Minahasa'],
            ['7109', 'Kabupaten Minahasa Selatan'],
            ['7110', 'Kabupaten Minahasa Tenggara'],
            ['7111', 'Kabupaten Minahasa Utara'],

            // 27) Provinsi Gorontalo (75)
            ['7571', 'Kota Gorontalo'],
            ['7501', 'Kabupaten Boalemo'],
            ['7502', 'Kabupaten Bone Bolango'],
            ['7503', 'Kabupaten Gorontalo'],
            ['7504', 'Kabupaten Gorontalo Utara'],
            ['7505', 'Kabupaten Pohuwato'],

            // 28) Provinsi Sulawesi Barat (76)
            ['7601', 'Kabupaten Majene'],
            ['7602', 'Kabupaten Mamasa'],
            ['7603', 'Kabupaten Mamuju'],
            ['7604', 'Kabupaten Mamuju Tengah'],
            ['7605', 'Kabupaten Pasangkayu'],
            ['7606', 'Kabupaten Polewali Mandar'],

            // 29) Provinsi Sulawesi Tengah (72)
            ['7271', 'Kota Palu'],
            ['7201', 'Kabupaten Banggai'],
            ['7202', 'Kabupaten Banggai Kepulauan'],
            ['7203', 'Kabupaten Banggai Laut'],
            ['7204', 'Kabupaten Buol'],
            ['7205', 'Kabupaten Donggala'],
            ['7206', 'Kabupaten Morowali'],
            ['7207', 'Kabupaten Morowali Utara'],
            ['7208', 'Kabupaten Parigi Moutong'],
            ['7209', 'Kabupaten Poso'],
            ['7210', 'Kabupaten Sigi'],
            ['7211', 'Kabupaten Tojo Una-Una'],
            ['7212', 'Kabupaten Tolitoli'],

            // 30) Provinsi Sulawesi Tenggara (74)
            ['7471', 'Kota Kendari'],
            ['7472', 'Kota Baubau'],
            ['7401', 'Kabupaten Bombana'],
            ['7402', 'Kabupaten Buton'],
            ['7403', 'Kabupaten Buton Selatan'],
            ['7404', 'Kabupaten Buton Tengah'],
            ['7405', 'Kabupaten Buton Utara'],
            ['7406', 'Kabupaten Kolaka'],
            ['7407', 'Kabupaten Kolaka Timur'],
            ['7408', 'Kabupaten Kolaka Utara'],
            ['7409', 'Kabupaten Konawe'],
            ['7410', 'Kabupaten Konawe Kepulauan'],
            ['7411', 'Kabupaten Konawe Selatan'],
            ['7412', 'Kabupaten Konawe Utara'],
            ['7413', 'Kabupaten Muna'],
            ['7414', 'Kabupaten Muna Barat'],
            ['7415', 'Kabupaten Wakatobi'],

            // 31) Provinsi Maluku (81)
            ['8171', 'Kota Ambon'],
            ['8172', 'Kota Tual'],
            ['8101', 'Kabupaten Buru'],
            ['8102', 'Kabupaten Buru Selatan'],
            ['8103', 'Kabupaten Kepulauan Aru'],
            ['8104', 'Kabupaten Kepulauan Tanimbar'],
            ['8105', 'Kabupaten Maluku Barat Daya'],
            ['8106', 'Kabupaten Maluku Tengah'],
            ['8107', 'Kabupaten Maluku Tenggara'],
            ['8108', 'Kabupaten Seram Bagian Barat'],
            ['8109', 'Kabupaten Seram Bagian Timur'],

            // 32) Provinsi Maluku Utara (82)
            ['8271', 'Kota Ternate'],
            ['8272', 'Kota Tidore Kepulauan'],
            ['8201', 'Kabupaten Halmahera Barat'],
            ['8202', 'Kabupaten Halmahera Tengah'],
            ['8203', 'Kabupaten Halmahera Utara'],
            ['8204', 'Kabupaten Halmahera Selatan'],
            ['8205', 'Kabupaten Halmahera Timur'],
            ['8206', 'Kabupaten Kepulauan Sula'],
            ['8207', 'Kabupaten Pulau Morotai'],
            ['8208', 'Kabupaten Pulau Taliabu'],

            // 33) Provinsi Papua (91)
            ['9171', 'Kota Jayapura'],
            ['9101', 'Kabupaten Jayapura'],
            ['9102', 'Kabupaten Keerom'],
            ['9103', 'Kabupaten Sarmi'],
            ['9104', 'Kabupaten Mamberamo Raya'],
            ['9105', 'Kabupaten Mamberamo Tengah'],
            ['9106', 'Kabupaten Yalimo'],
            ['9107', 'Kabupaten Waropen'],
            ['9108', 'Kabupaten Supiori'],
            ['9109', 'Kabupaten Jayawijaya'],
            ['9110', 'Kabupaten Pegunungan Bintang'],
            ['9111', 'Kabupaten Yahukimo'],
            ['9112', 'Kabupaten Tolikara'],
            ['9113', 'Kabupaten Lanny Jaya'],
            ['9114', 'Kabupaten Nduga'],
            ['9115', 'Kabupaten Merauke'],
            ['9116', 'Kabupaten Asmat'],
            ['9117', 'Kabupaten Boven Digoel'],
            ['9118', 'Kabupaten Mappi'],
            ['9119', 'Kabupaten Nabire'],
            ['9120', 'Kabupaten Mimika'],
            ['9121', 'Kabupaten Paniai'],
            ['9122', 'Kabupaten Dogiyai'],
            ['9123', 'Kabupaten Deiyai'],
            ['9124', 'Kabupaten Intan Jaya'],
            ['9125', 'Kabupaten Puncak'],
            ['9126', 'Kabupaten Puncak Jaya'],

            // 34) Provinsi Papua Barat (92)
            ['9271', 'Kota Sorong'],
            ['9201', 'Kabupaten Manokwari'],
            ['9202', 'Kabupaten Manokwari Selatan'],
            ['9203', 'Kabupaten Pegunungan Arfak'],
            ['9204', 'Kabupaten Teluk Bintuni'],
            ['9205', 'Kabupaten Teluk Wondama'],
            ['9206', 'Kabupaten Kaimana'],
            ['9207', 'Kabupaten Fakfak'],
            ['9208', 'Kabupaten Sorong'],
            ['9209', 'Kabupaten Sorong Selatan'],
            ['9210', 'Kabupaten Raja Ampat'],
            ['9211', 'Kabupaten Tambrauw'],
            ['9212', 'Kabupaten Maybrat'],
        ];

        $now = \Carbon\Carbon::now();

        foreach ($kabkota as [$kode, $nama]) {
            // 1. Ambil 2 digit pertama dari kode untuk mencari Provinsi induknya
            $kodeProv = substr($kode, 0, 2);

            // 2. Cari data provinsi di database yang kode_wilayah-nya cocok dan tingkatnya 2 (Provinsi)
            $provinsi = DB::table('wilayah')
                ->where('kode_wilayah', $kodeProv)
                ->where('tingkat_wilayah_id', 2)
                ->first();

            // Jika provinsinya tidak ketemu di database, lewati (skip) agar tidak error
            if (!$provinsi) {
                continue; 
            }

            // =====================================================================
            // 3. FITUR AMAN (MENCEGAH REPLACE/DELETE DATA LAMA)
            // Sistem mengecek apakah wilayah dengan kode ini (misal: 1171) sudah ada.
            // =====================================================================
            $exists = DB::table('wilayah')->where('kode_wilayah', $kode)->first();

            // Jika data BELUM ADA di database, maka Insert sebagai data baru
            if (!$exists) {
                DB::table('wilayah')->insert([
                    'id'                 => (string) \Illuminate\Support\Str::uuid(), // Buat UUID baru
                    'kode_wilayah'       => $kode,
                    'nama_wilayah'       => $nama,
                    'tingkat_wilayah_id' => 3, // Set otomatis ke Tingkat Kabupaten/Kota
                    'parent_wilayah_id'  => $provinsi->id, // Sambungkan ke UUID provinsi induk
                    'created_at'         => $now,
                    'updated_at'         => $now,
                ]);
            }
        }
    }
}
